### PR TITLE
Fix infinite loading when there is a Gql error

### PR DESCRIPTION
**Pull request by Gherciu**

### CODE REVIEW

**Comment by Gherciu** [comment]
@meabed 

This PR resolves a issue related to Graphql errors

What I noticed is that 
req.end event is never called if there is a Graphql Error (For example UI sent a incorrect Graphql Type)
And the method was just infinitely waiting
Also I didn't understand why the wrapper around `send` is needed
but seems that without it everything works just Fine

**Comment by meabed** [comment]
Thank you @Gherciu 
Would you be able to share a code sandbox with the error.

I use this currently in express without having any issues?

**Comment by Alex0007** [comment]
@meabed i faced that problem several hours ago and this PR actually solves it

**Comment by meabed** [comment]
Thanks @Alex0007 would you be able to put a codesanbox to reproduce this

**Comment by Alex0007** [comment]
@meabed 

This issue describes source of problem: when error is thrown in resolver – no response is sent, request just stuck for infinite amount of time. Sadly i don't know how to quickly create example to reproduce. But pseudo-code in issue literally describes problem. 

https://github.com/meabed/graphql-upload-ts/issues/78#issue-1486342340

**Comment by meabed** [comment]
@Gherciu @Alex0007 

Thank you I have added an optional flag here: https://github.com/meabed/graphql-upload-ts/pull/175/commits/dacdb36af4653eeb0df1246b8849d45789521969


Will test it and publish soon

**Comment by meabed** [comment]
Seems working for me ✅ I will release this

**Comment by meabed** [comment]
Fixed in https://github.com/meabed/graphql-upload-ts/pull/175

**Pull request closed without merging**
